# This is a basic workflow to help you get started with Actions

name: Build UEFI for a given device

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

# Indicate that we are running in CI
env:
  WM_CI_BUILD: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains one job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Build SecureBoot and No SecureBoot UEFI for ${{ inputs.target }}
        run: bash scripts/ci_setup.sh && ./build_uefi.py -d ${{ inputs.target }}

      - name: Upload ${{ inputs.target }}'s Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uefi-images-${{ inputs.target }}
          path: Build/*/ci_artifacts
          compression-level: 9